#!/bin/sh /etc/rc.common

START=94
STOP=16

CONTROLLER=/usr/libexec/wloc/firewall.uc

start() {
    /usr/bin/ucode "$CONTROLLER" apply-effective >/dev/null
}

stop() {
    /usr/bin/ucode "$CONTROLLER" remove-runtime >/dev/null
}
